name: Apply to Staging

on:
    workflow_dispatch:
    push:
      branches:
        - 'feat-*'
        - 'fix-*'
        - 'docs-*'
        - 'style-*'
        - 'refactor-*'
        - 'test-*'
        - 'chore-*'
        - 'build-*'
        - 'ci-*'
        - 'perf-*'
      paths:
        - '**/*.tf'


jobs:
  check-branch-name:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: execute branch check script
        run: |
          chmod +x .github/supporting_scripts/branch_check.sh
          ./.github/supporting_scripts/branch_check.sh

        shell: bash