name: Demo - 1 - Apply - Staging

on:
    workflow_dispatch:
    push:
      branches:
        - 'feat-*'
        - 'bugfix-*'

jobs:
  check-branch-name:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: execute branch check script
        run: |
          chmod +x .github/scripts/branch_check.sh
          ./.github/scripts/branch_check.sh

        shell: bash