name: Demo | 1 - Plan - Staging

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]
    
    branches:
      - main

    # paths:
    #   - '**.tf'


jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: execute branch check script
        run: |
          chmod +x .github/scripts/branch_check.sh
          ./.github/scripts/branch_check.sh

        shell: bash
