on:
  push:
    branches:
    - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/create-github-app-token@v1
      id: app-token
      with:
        token: ${{ secrets.PAT_TOKEN }}

    - uses: googleapis/release-please-action@v4
      with:
        token: ${{ steps.app-token.outputs.token }}
        release-type: simple
