name: Test - Run Python Script in Docker

on:
    workflow_call:
      inputs:
        file-name:
          required: true
          type: string

jobs:
  update-pr:
    runs-on: ubuntu-latest

    permissions:
      packages: read
      pull-requests: write
      contents: write

    container:
      image: ghcr.io/${{ github.repository }}/python:latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        HEAD_BRANCH: feat-test
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Python Script
        run: python .github/scripts/create_update_pr.py


    
   