name: Test - Run Python Script in Docker

on:
  workflow_dispatch:
    inputs:
      pr-ref:
        required: true
        type: string

  workflow_call:
    # inputs:
    #   pr-ref:
    #     required: true
    #     type: string

jobs:
  update-pr:
    runs-on: ubuntu-latest

    permissions:
      packages: read
      pull-requests: write
      contents: write

    container:
      image: ghcr.io/${{ github.repository }}/python:latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        HEAD_BRANCH: feat-test
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Python Script
        run: python .github/scripts/update_pr.py


    
   