name: Python Test

on:
    workflow_dispatch:

jobs:
  update-pr:
    runs-on: ubuntu-latest
    # container:
    #   image: ghcr.io/${{ github.repository }}/python_test:latest
    #   credentials:
    #     username: ${{ github.actor }}
    #     password: ${{ secrets.GITHUB_TOKEN }}

    permissions:
      packages: read
      pull-requests: write
      contents: write
    
    steps:
      - uses: actions/checkout@v4
      
      # - name: Set up Python
      #   uses: actions/setup-python@v5.2.0
      #   with:
      #     python-version: '3.x'
      
      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install PyGithub
      
      # - name: Run PR manager
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     HEAD_BRANCH: "feat-test"
      #   run: python .github/scripts/pr.py

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Python Script
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/python_test \
            -w /python_test \
            ghcr.io/${{ github.repository }}/python_test:latest \
            python .github/scripts/create_update_pr.py \
            -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
            -e HEAD_BRANCH="feat-test"