name: Python Test

on:
    workflow_dispatch:

jobs:
  update-pr:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/python_test:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    permissions:
      pull-requests: write
      contents: write
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub
      
      - name: Run PR manager
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HEAD_BRANCH: "feat-test"
        run: python .github/scripts/pr.py