name: Python Test

on:
    workflow_dispatch:

jobs:
  update-pr:
    runs-on: ubuntu-latest

    permissions:
      packages: read
      pull-requests: write
      contents: write

    container:
      image: ghcr.io/${{ github.repository }}/app:latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        HEAD_BRANCH: feat-test
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Python Script
        run: python .github/scripts/create_update_pr.py


    
   